'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(2),  _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")>  _
Partial Public NotInheritable Class Planilha2
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase
    
    Friend WithEvents TB_UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_DOCENTES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_UNIDADES_EDUCACIONAIS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_BLOCOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_ANDARES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_SALAS_DE_AULA As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_AUTORIZACOES_PARA_LECIONAR As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_ATESTADOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_FERIADOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_RECESSOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_DATAS_EVENTUAIS_POR_TURMA As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_PROJETOS_INTEGRADORES As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_ESTAGIOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_HORARIOS As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TB_NIVEIS_ACESSO As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CRONOGRAMA__ID_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CURSO__CODIGO_CURSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CURSO__ID_CURSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_CURSO__NOME_CURSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_LISTA__DOCENTES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_LISTA__SALAS_DE_AULA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_LISTA__UNIDADES_CURRICULARES As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ANO_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__DATA_INICIO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_CURSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_ENUM_TURNO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_NUMERO_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_TURMA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA As Microsoft.Office.Tools.Excel.NamedRange
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Planilha2", "Planilha2")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub Initialize()
        MyBase.Initialize
        Globals.Planilha2 = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles
        Me.InitializeCachedData
        Me.InitializeControls
        Me.InitializeComponents
        Me.InitializeData
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization
        Me.BindToData
        Me.EndInitialization
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BindToData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BeginInitialization()
        Me.BeginInit
        Me.TB_UNIDADES_CURRICULARES.BeginInit
        Me.TB_DOCENTES.BeginInit
        Me.TB_UNIDADES_EDUCACIONAIS.BeginInit
        Me.TB_BLOCOS.BeginInit
        Me.TB_ANDARES.BeginInit
        Me.TB_SALAS_DE_AULA.BeginInit
        Me.TB_AUTORIZACOES_PARA_LECIONAR.BeginInit
        Me.TB_ATESTADOS.BeginInit
        Me.TB_FERIADOS.BeginInit
        Me.TB_RECESSOS.BeginInit
        Me.TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL.BeginInit
        Me.TB_DATAS_EVENTUAIS_POR_TURMA.BeginInit
        Me.TB_PROJETOS_INTEGRADORES.BeginInit
        Me.TB_ESTAGIOS.BeginInit
        Me.TB_HORARIOS.BeginInit
        Me.TB_NIVEIS_ACESSO.BeginInit
        Me.CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL.BeginInit
        Me.CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL.BeginInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO.BeginInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA.BeginInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO.BeginInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO.BeginInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA.BeginInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_TURMA.BeginInit
        Me.CONFIGURACAO_CURSO__CODIGO_CURSO.BeginInit
        Me.CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL.BeginInit
        Me.CONFIGURACAO_CURSO__ID_CURSO.BeginInit
        Me.CONFIGURACAO_CURSO__NOME_CURSO.BeginInit
        Me.CONFIGURACAO_LISTA__DOCENTES.BeginInit
        Me.CONFIGURACAO_LISTA__SALAS_DE_AULA.BeginInit
        Me.CONFIGURACAO_LISTA__UNIDADES_CURRICULARES.BeginInit
        Me.CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS.BeginInit
        Me.CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL.BeginInit
        Me.CONFIGURACAO_TURMA__ANO_TURMA.BeginInit
        Me.CONFIGURACAO_TURMA__DATA_INICIO.BeginInit
        Me.CONFIGURACAO_TURMA__ID_CURSO.BeginInit
        Me.CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA.BeginInit
        Me.CONFIGURACAO_TURMA__ID_ENUM_TURNO.BeginInit
        Me.CONFIGURACAO_TURMA__ID_NUMERO_TURMA.BeginInit
        Me.CONFIGURACAO_TURMA__ID_TURMA.BeginInit
        Me.CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO.BeginInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA.BeginInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub EndInitialization()
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE.EndInit
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO.EndInit
        Me.CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL.EndInit
        Me.CONFIGURACAO_TURMA__ID_TURMA.EndInit
        Me.CONFIGURACAO_TURMA__ID_NUMERO_TURMA.EndInit
        Me.CONFIGURACAO_TURMA__ID_ENUM_TURNO.EndInit
        Me.CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA.EndInit
        Me.CONFIGURACAO_TURMA__ID_CURSO.EndInit
        Me.CONFIGURACAO_TURMA__DATA_INICIO.EndInit
        Me.CONFIGURACAO_TURMA__ANO_TURMA.EndInit
        Me.CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL.EndInit
        Me.CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS.EndInit
        Me.CONFIGURACAO_LISTA__UNIDADES_CURRICULARES.EndInit
        Me.CONFIGURACAO_LISTA__SALAS_DE_AULA.EndInit
        Me.CONFIGURACAO_LISTA__DOCENTES.EndInit
        Me.CONFIGURACAO_CURSO__NOME_CURSO.EndInit
        Me.CONFIGURACAO_CURSO__ID_CURSO.EndInit
        Me.CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL.EndInit
        Me.CONFIGURACAO_CURSO__CODIGO_CURSO.EndInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_TURMA.EndInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA.EndInit
        Me.CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO.EndInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO.EndInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA.EndInit
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO.EndInit
        Me.CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL.EndInit
        Me.CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL.EndInit
        Me.TB_NIVEIS_ACESSO.EndInit
        Me.TB_HORARIOS.EndInit
        Me.TB_ESTAGIOS.EndInit
        Me.TB_PROJETOS_INTEGRADORES.EndInit
        Me.TB_DATAS_EVENTUAIS_POR_TURMA.EndInit
        Me.TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL.EndInit
        Me.TB_RECESSOS.EndInit
        Me.TB_FERIADOS.EndInit
        Me.TB_ATESTADOS.EndInit
        Me.TB_AUTORIZACOES_PARA_LECIONAR.EndInit
        Me.TB_SALAS_DE_AULA.EndInit
        Me.TB_ANDARES.EndInit
        Me.TB_BLOCOS.EndInit
        Me.TB_UNIDADES_EDUCACIONAIS.EndInit
        Me.TB_DOCENTES.EndInit
        Me.TB_UNIDADES_CURRICULARES.EndInit
        Me.EndInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeControls()
        Me.TB_UNIDADES_CURRICULARES = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_UNIDADES_CURRICULARES", "TB_UNIDADES_CURRICULARES", Me)
        Me.TB_DOCENTES = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_DOCENTES", "TB_DOCENTES", Me)
        Me.TB_UNIDADES_EDUCACIONAIS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_UNIDADES_EDUCACIONAIS", "TB_UNIDADES_EDUCACIONAIS", Me)
        Me.TB_BLOCOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_BLOCOS", "TB_BLOCOS", Me)
        Me.TB_ANDARES = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_ANDARES", "TB_ANDARES", Me)
        Me.TB_SALAS_DE_AULA = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_SALAS_DE_AULA", "TB_SALAS_DE_AULA", Me)
        Me.TB_AUTORIZACOES_PARA_LECIONAR = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_AUTORIZACOES_PARA_LECIONAR", "TB_AUTORIZACOES_PARA_LECIONAR", Me)
        Me.TB_ATESTADOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_ATESTADOS", "TB_ATESTADOS", Me)
        Me.TB_FERIADOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_FERIADOS", "TB_FERIADOS", Me)
        Me.TB_RECESSOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_RECESSOS", "TB_RECESSOS", Me)
        Me.TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL", "TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL", Me)
        Me.TB_DATAS_EVENTUAIS_POR_TURMA = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_DATAS_EVENTUAIS_POR_TURMA", "TB_DATAS_EVENTUAIS_POR_TURMA", Me)
        Me.TB_PROJETOS_INTEGRADORES = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_PROJETOS_INTEGRADORES", "TB_PROJETOS_INTEGRADORES", Me)
        Me.TB_ESTAGIOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_ESTAGIOS", "TB_ESTAGIOS", Me)
        Me.TB_HORARIOS = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_HORARIOS", "TB_HORARIOS", Me)
        Me.TB_NIVEIS_ACESSO = Globals.Factory.CreateListObject(Nothing, Nothing, "Planilha2:TB_NIVEIS_ACESSO", "TB_NIVEIS_ACESSO", Me)
        Me.CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL", "CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL", Me)
        Me.CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL", "CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL", Me)
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO", "CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO", Me)
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA", "CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA", Me)
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO", "CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO", Me)
        Me.CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO", "CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO", Me)
        Me.CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA", "CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA", Me)
        Me.CONFIGURACAO_CRONOGRAMA__ID_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CRONOGRAMA__ID_TURMA", "CONFIGURACAO_CRONOGRAMA__ID_TURMA", Me)
        Me.CONFIGURACAO_CURSO__CODIGO_CURSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CURSO__CODIGO_CURSO", "CONFIGURACAO_CURSO__CODIGO_CURSO", Me)
        Me.CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL", "CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL", Me)
        Me.CONFIGURACAO_CURSO__ID_CURSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CURSO__ID_CURSO", "CONFIGURACAO_CURSO__ID_CURSO", Me)
        Me.CONFIGURACAO_CURSO__NOME_CURSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_CURSO__NOME_CURSO", "CONFIGURACAO_CURSO__NOME_CURSO", Me)
        Me.CONFIGURACAO_LISTA__DOCENTES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_LISTA__DOCENTES", "CONFIGURACAO_LISTA__DOCENTES", Me)
        Me.CONFIGURACAO_LISTA__SALAS_DE_AULA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_LISTA__SALAS_DE_AULA", "CONFIGURACAO_LISTA__SALAS_DE_AULA", Me)
        Me.CONFIGURACAO_LISTA__UNIDADES_CURRICULARES = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_LISTA__UNIDADES_CURRICULARES", "CONFIGURACAO_LISTA__UNIDADES_CURRICULARES", Me)
        Me.CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS", "CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS", Me)
        Me.CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL", "CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL", Me)
        Me.CONFIGURACAO_TURMA__ANO_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ANO_TURMA", "CONFIGURACAO_TURMA__ANO_TURMA", Me)
        Me.CONFIGURACAO_TURMA__DATA_INICIO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__DATA_INICIO", "CONFIGURACAO_TURMA__DATA_INICIO", Me)
        Me.CONFIGURACAO_TURMA__ID_CURSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_CURSO", "CONFIGURACAO_TURMA__ID_CURSO", Me)
        Me.CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA", "CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA", Me)
        Me.CONFIGURACAO_TURMA__ID_ENUM_TURNO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_ENUM_TURNO", "CONFIGURACAO_TURMA__ID_ENUM_TURNO", Me)
        Me.CONFIGURACAO_TURMA__ID_NUMERO_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_NUMERO_TURMA", "CONFIGURACAO_TURMA__ID_NUMERO_TURMA", Me)
        Me.CONFIGURACAO_TURMA__ID_TURMA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_TURMA", "CONFIGURACAO_TURMA__ID_TURMA", Me)
        Me.CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL", "CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO", "CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE", "CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO", "CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO", "CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL", "CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO", "CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME", "CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO", "CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO", Me)
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA", "CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA", Me)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeComponents()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub OnShutdown()
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__SIGLA.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NUMERO.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__NOME.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__LOGRADOURO.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ID_UNIDADE_EDUCACIONAL.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__ESTADO.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CODIGO.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__CIDADE.Dispose
        Me.CONFIGURACAO_UNIDADE_EDUCACIONAL__BAIRRO.Dispose
        Me.CONFIGURACAO_TURMA__ID_UNIDADE_EDUCACIONAL.Dispose
        Me.CONFIGURACAO_TURMA__ID_TURMA.Dispose
        Me.CONFIGURACAO_TURMA__ID_NUMERO_TURMA.Dispose
        Me.CONFIGURACAO_TURMA__ID_ENUM_TURNO.Dispose
        Me.CONFIGURACAO_TURMA__ID_ENUM_TIPO_TURMA.Dispose
        Me.CONFIGURACAO_TURMA__ID_CURSO.Dispose
        Me.CONFIGURACAO_TURMA__DATA_INICIO.Dispose
        Me.CONFIGURACAO_TURMA__ANO_TURMA.Dispose
        Me.CONFIGURACAO_SISTEMA__ID_USUARIO_ATUAL.Dispose
        Me.CONFIGURACAO_SISTEMA__CAMINHO_BANCO_DE_DADOS.Dispose
        Me.CONFIGURACAO_LISTA__UNIDADES_CURRICULARES.Dispose
        Me.CONFIGURACAO_LISTA__SALAS_DE_AULA.Dispose
        Me.CONFIGURACAO_LISTA__DOCENTES.Dispose
        Me.CONFIGURACAO_CURSO__NOME_CURSO.Dispose
        Me.CONFIGURACAO_CURSO__ID_CURSO.Dispose
        Me.CONFIGURACAO_CURSO__ID_AREA_PROFISSIONAL.Dispose
        Me.CONFIGURACAO_CURSO__CODIGO_CURSO.Dispose
        Me.CONFIGURACAO_CRONOGRAMA__ID_TURMA.Dispose
        Me.CONFIGURACAO_CRONOGRAMA__ID_CRONOGRAMA.Dispose
        Me.CONFIGURACAO_CRONOGRAMA__ID_CALENDARIO_ACADEMICO.Dispose
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__VERSAO.Dispose
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_TURMA.Dispose
        Me.CONFIGURACAO_CALENDARIO_ACADEMICO__ID_CALENDARIO_ACADEMICO.Dispose
        Me.CONFIGURACAO_AREA_PROFISSIONAL__NOME_AREA_PROFISSIONAL.Dispose
        Me.CONFIGURACAO_AREA_PROFISSIONAL__ID_AREA_PROFISSIONAL.Dispose
        Me.TB_NIVEIS_ACESSO.Dispose
        Me.TB_HORARIOS.Dispose
        Me.TB_ESTAGIOS.Dispose
        Me.TB_PROJETOS_INTEGRADORES.Dispose
        Me.TB_DATAS_EVENTUAIS_POR_TURMA.Dispose
        Me.TB_DATAS_EVENTUAIS_POR_UNIDADE_EDUCACIONAL.Dispose
        Me.TB_RECESSOS.Dispose
        Me.TB_FERIADOS.Dispose
        Me.TB_ATESTADOS.Dispose
        Me.TB_AUTORIZACOES_PARA_LECIONAR.Dispose
        Me.TB_SALAS_DE_AULA.Dispose
        Me.TB_ANDARES.Dispose
        Me.TB_BLOCOS.Dispose
        Me.TB_UNIDADES_EDUCACIONAIS.Dispose
        Me.TB_DOCENTES.Dispose
        Me.TB_UNIDADES_CURRICULARES.Dispose
        MyBase.OnShutdown
    End Sub
End Class

Partial Friend NotInheritable Class Globals
    
    Private Shared _Planilha2 As Planilha2
    
    Friend Shared Property Planilha2() As Planilha2
        Get
            Return _Planilha2
        End Get
        Set
            If (_Planilha2 Is Nothing) Then
                _Planilha2 = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
