'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(6),  _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")>  _
Partial Public NotInheritable Class Planilha6
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase
    
    Friend WithEvents Planilha6_Print_Area As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__ANO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9 As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents Planilha6_Print_Titles As Microsoft.Office.Tools.Excel.NamedRange
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Planilha6", "Planilha6")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub Initialize()
        MyBase.Initialize
        Globals.Planilha6 = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles
        Me.InitializeCachedData
        Me.InitializeControls
        Me.InitializeComponents
        Me.InitializeData
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization
        Me.BindToData
        Me.EndInitialization
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BindToData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BeginInitialization()
        Me.BeginInit
        Me.Planilha6_Print_Area.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9.BeginInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8.BeginInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9.BeginInit
        Me.Planilha6_Print_Titles.BeginInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub EndInitialization()
        Me.Planilha6_Print_Titles.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10.EndInit
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANO.EndInit
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR.EndInit
        Me.Planilha6_Print_Area.EndInit
        Me.EndInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeControls()
        Me.Planilha6_Print_Area = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!Print_Area", "Planilha6_Print_Area", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__ANDAR", "Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__ANO", "Planilha6_MAPA_DE_SALA_CABECALHO__ANO", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__BLOCO", "Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__NOME_ESPACO", "Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__NUMERO_SALA", "Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__TURNO_LETIVO", "Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL", "Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL", Me)
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CABECALHO__VERSAO", "Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9", Me)
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_CRONOGRAMA__MATRIZ", "Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9", "Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS", "Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__COR_FERIADO", "Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__COR_RECESSO", "Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_1", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_10", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_11", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_12", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_13", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_14", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_15", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_16", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_17", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_18", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_19", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_2", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_20", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_21", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_22", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_23", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_24", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_25", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_26", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_27", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_28", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_29", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_3", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_30", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_31", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_32", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_33", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_34", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_35", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_36", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_37", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_38", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_39", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_4", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_40", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_5", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_6", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_7", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_8", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__NOME_CURSO_9", "Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_1", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_10", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_11", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_12", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_13", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_14", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_15", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_16", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_17", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_18", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_19", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_2", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_20", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_21", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_22", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_23", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_24", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_25", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_26", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_27", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_28", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_29", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_3", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_30", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_31", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_32", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_33", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_34", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_35", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_36", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_37", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_38", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_39", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_4", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_40", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_5", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_6", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_7", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_8", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8", Me)
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9 = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!MAPA_DE_SALA_LEGENDA__TURMA_9", "Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9", Me)
        Me.Planilha6_Print_Titles = Globals.Factory.CreateNamedRange(Nothing, Nothing, "Planilha6!Print_Titles", "Planilha6_Print_Titles", Me)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeComponents()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "17.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub OnShutdown()
        Me.Planilha6_Print_Titles.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_40.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_39.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_38.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_37.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_36.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_35.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_34.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_33.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_32.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_31.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_30.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_29.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_28.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_27.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_26.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_25.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_24.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_23.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_22.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_21.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_20.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_19.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_18.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_17.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_16.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_15.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_14.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_13.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__TURMA_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_40.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_39.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_38.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_37.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_36.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_35.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_34.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_33.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_32.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_31.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_30.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_29.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_28.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_27.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_26.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_25.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_24.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_23.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_22.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_21.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_20.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_19.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_18.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_17.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_16.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_15.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_14.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_13.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__NOME_CURSO_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_RECESSO.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_FERIADO.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__COR_CONFLITO_DE_TURMAS.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_40.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_39.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_38.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_37.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_36.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_35.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_34.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_33.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_32.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_31.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_30.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_29.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_28.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_27.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_26.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_25.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_24.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_23.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_22.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_21.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_20.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_19.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_18.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_17.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_16.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_15.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_14.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_13.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_LEGENDA__CODIGO_TURMA_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__MATRIZ.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_NOME_MES_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_MES_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_9.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_8.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_7.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_6.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_5.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_4.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_3.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_2.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_12.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_11.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_10.Dispose
        Me.Planilha6_MAPA_DE_SALA_CRONOGRAMA__BASE_LEGENDA_MES_1.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__VERSAO.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__UNIDADE_EDUCACIONAL.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__TURNO_LETIVO.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NUMERO_SALA.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__NOME_ESPACO.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__BLOCO.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANO.Dispose
        Me.Planilha6_MAPA_DE_SALA_CABECALHO__ANDAR.Dispose
        Me.Planilha6_Print_Area.Dispose
        MyBase.OnShutdown
    End Sub
End Class

Partial Friend NotInheritable Class Globals
    
    Private Shared _Planilha6 As Planilha6
    
    Friend Shared Property Planilha6() As Planilha6
        Get
            Return _Planilha6
        End Get
        Set
            If (_Planilha6 Is Nothing) Then
                _Planilha6 = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
