'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    'através de uma ferramenta como ResGen ou Visual Studio.
    'Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    'com a opção /str, ou recrie o projeto do VS.
    '''<summary>
    '''  Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("S.A.G.E.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Substitui a propriedade CurrentUICulture do thread atual para todas as
        '''  pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Criacao_CriarComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Criacao_CriarComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Criacao_RecriarComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Criacao_RecriarComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Edicao_EditarCronogramaManualmente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Edicao_EditarCronogram"& _ 
                        "aManualmente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao_EmPDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao_EmPDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao_EmXLSX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao_EmXLSX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Validacao_VisualizarErros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Validacao_VisualizarEr"& _ 
                        "ros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_VisualizarCalendarioAcademico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_VisualizarCalendarioAc"& _ 
                        "ademico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_VisualizarCronograma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_VisualizarCronograma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasDeEstagiosProfissionaisSupervisionados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasDeE"& _ 
                        "stagiosProfissionaisSupervisionados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasDeProjetosIntegradores() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasDeP"& _ 
                        "rojetosIntegradores", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasEventuaisPorTurma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_GestaoDeEventos_GerenciarDatasEve"& _ 
                        "ntuaisPorTurma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_VoltarPara_MenuInicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_CalendarioAcademico_VoltarPara_MenuInicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Criacao_CriarComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Criacao_CriarComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Criacao_RecriarComIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Criacao_RecriarComIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao_EmPDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao_EmPDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao_EmXLSX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao_EmXLSX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Validacao_VisualizarErros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Validacao_VisualizarErros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Visualizacao_VisualizarCronograma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Visualizacao_VisualizarCronogra"& _ 
                        "ma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Visualizacao_VisualizarMapaDeSala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_Cronograma_Visualizacao_VisualizarMapaDeSa"& _ 
                        "la", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_EdicaoDeCronograma_MapaDeSala_VoltarPara_MenuInicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_EdicaoDeCronograma_MapaDeSala_VoltarPara_MenuInicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_InformacoesSobreOSistema_Configuracoes_BancoDeDados_ReconfigurarBancoDeDados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_InformacoesSobreOSistema_Configuracoes_BancoDeDados_ReconfigurarBancoDeD"& _ 
                        "ados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_InformacoesSobreOSistema_Configuracoes_ConfigurarBancoDeDados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_InformacoesSobreOSistema_Configuracoes_ConfigurarBancoDeDados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_Logon_Configuracao_Informacoes_UsuarioLogado_SolicitarAcessoViaTeams() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_Logon_Configuracao_Informacoes_UsuarioLogado_SolicitarAcessoViaTeams", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_Logon_Login_IniciarSessao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_Logon_Login_IniciarSessao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarAreasProfissionais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarAreasProfissionais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarCursos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarCursos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarUnidadesCurriculares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoAcademica_GerenciarUnidadesCurriculares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeAcessos_GerenciarAcessosDeUsuarios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeAcessos_GerenciarAcessosDeUsuarios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeAcessos_GerenciarUsuarios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeAcessos_GerenciarUsuarios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarDatasEventuaisPorUnidadeEducacional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarDatasEventuaisPorUnid"& _ 
                        "adeEducacional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarFeriados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarFeriados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarRecessos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeEventos_GerenciarRecessos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarAndares() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarAndares", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarBlocos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarBlocos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarSalas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarSalas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarUnidadesEducacionais() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoDeInfraestrutura_GerenciarUnidadesEducac"& _ 
                        "ionais", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarAtestados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarAtestados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarAutorizacoesParaLecionar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarAutorizacoesParaLec"& _ 
                        "ionar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarDocentes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Configuracoes_GestaoEducacional_GerenciarDocentes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Cronogramas_GestaoDeCalendariosAcademicos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Cronogramas_GestaoDeCalendariosAcademicos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Cronogramas_GestaoDeMapasDeSala() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Cronogramas_GestaoDeMapasDeSala", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Bttn_MenuInicial_Logout_FinalizarSessao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Bttn_MenuInicial_Logout_FinalizarSessao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_EdicaoDeCronograma_CalendarioAcademico_Cronograma_Exportacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_EdicaoDeCronograma_MapaDeSala_Cronograma_Exportacao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_MenuInicial_Configuracoes_GestaoAcademica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_MenuInicial_Configuracoes_GestaoAcademica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_MenuInicial_Configuracoes_GestaoDeAcessos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_MenuInicial_Configuracoes_GestaoDeAcessos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_MenuInicial_Configuracoes_GestaoDeEventos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_MenuInicial_Configuracoes_GestaoDeEventos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_MenuInicial_Configuracoes_GestaoDeInfraestrutura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_MenuInicial_Configuracoes_GestaoDeInfraestrutura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Mn_MenuInicial_Configuracoes_GestaoEducacional() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Mn_MenuInicial_Configuracoes_GestaoEducacional", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icn_Padrao() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icn_Padrao", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Img_ImgCntrl_InformacoesSobreOSistema_Sistema_Logomarca() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Img_ImgCntrl_InformacoesSobreOSistema_Sistema_Logomarca", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
